### ISSUE TITLE
Bug: `createAISDKTools` result in `TypeError: Cannot read properties of undefined (reading 'name')`

### ISSUE THREAD

**Issue by nirtamir2** [transitive-bullshit/agentic#646]
I tried to run Wikipedia agent:
```ts
import { WikipediaClient } from "@agentic/stdlib";
import { createAISDKTools } from "@agentic/stdlib/ai-sdk";

const wikipedia = new WikipediaClient();
const tools = createAISDKTools(wikipedia);
```

And I got an error here after executing `createAISDKTools(wikipedia)`
```
TypeError: Cannot read properties of undefined (reading 'name')
```

Same happens with weather client too.

**Comment by transitive-bullshit** [comment]
Thanks for the report @nirtamir2

I was able to repro the bug, but the odd thing is that it doesn't repro on all platforms. It seems to be an issue with `instanceof` not working correctly for the transpiled JS classes.

Anyhow, I made `AIFunctionSet` more robust and added some tests to ensure this doesn't regress. This should be fixed in the latest release: https://github.com/transitive-bullshit/agentic/releases/tag/v6.2.4

Thanks!
