### ISSUE TITLE
should @agentic/core be a dependency (not a devDependency)?

### ISSUE THREAD

**Issue by pelikhan** [transitive-bullshit/agentic#663]
I noticed that the @agentic/core package was declared in devDependencies instead of dependencies (https://github.com/transitive-bullshit/agentic/blob/main/packages/calculator/package.json#L42). I wonder if this is by design or just an oversight. Currently one has to install @agentic/core and @agenict/toolname to make things work.

**Comment by transitive-bullshit** [comment]
If you're using a single tool, I agree it's annoying to have to install `@agentic/core`, `@agentic/toolname`, and `zod` just to use one tool.

This is working as currently intended, though, since I've found that most of the time I want to use multiple tools and not have `@agentic/core` be shared as transitive deps multiple-times (or possibly have multiple different versions).

So `@agentic/core` is a peer dep of all agentic packages and is included locally as a dev dep so they have access to types.

The import situation is a little more complex than I would like, so I'm definitely open to feedback, especially for GenAIScript's use case.

**Comment by pelikhan** [comment]
Fair enough. The fix is to always install @agentic/core and @agentic/tool alongside. Maybe the docs should mention that.

**Comment by transitive-bullshit** [comment]
> Fair enough. The fix is to always install @agentic/core and @agentic/tool alongside. Maybe the docs should mention that.

Will update the tool docs shortly; I agree it is def more confusing that I'd like.

Thanks!

**Comment by pelikhan** [comment]
[like]  Peli de Halleux reacted to your message:
________________________________

**Comment by pelikhan** [comment]
I even wrote a blog post manually (i know, so 2010...) about the added support. https://microsoft.github.io/genaiscript/blog/support-for-agentic-tools/
